version: "3.9"  # Ensure you're using a supported version

services:
  server:
    container_name: codeSphere-server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./server:/app
      - /build/node_modules
    networks:
      - Code-Sync  # Reference to the defined network
    ports:
      - "3000:3000"

  client:
    container_name: codeSphere-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./client:/app
      - /build/node_modules
    networks:
      - codeSphere # Reference to the same network
    ports:
      - "5173:5173"
    depends_on:
      - server

networks:
   codeSphere:
    driver: bridge  # Use the default bridge driver
